image: registry.spring26b.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build

.test:
  image: python:3.12-slim
  stage: test
  services:
    - name: postgres:15-alpine
      alias: postgres 
    - name: redis:7-alpine
      alias: redis
    # 🌟 新增：挂载你之前固化了密码的自定义 MinIO 镜像作为测试伴生服务
    # 注意：请将下方的镜像路径替换为你 MinIO 仓库在 SECoder 上的真实 Registry 地址
    - name: minio/minio:RELEASE.2022-05-26T05-48-41Z
      alias: im-minio.default.secoder.local  # 核心：别名必须和 core/config.py 里写死的线上域名完全一致！
      command: ["server", "/data", "--address", ":9000"]
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "123456"
    POSTGRES_DB: postgres
    # 🌟 关键修改：在这里把密码灌给官方镜像，和你的代码无缝对上暗号
    MINIO_ROOT_USER: "IM_Admin_8w2P"
    MINIO_ROOT_PASSWORD: "X9vM4cK7zL1qN5bY"
    MINIO_BROWSER: "off"

    # 🌟🌟🌟 新增：专门给你的 FastAPI 后端代码用的 🌟🌟🌟
    S3_ENDPOINT: "im-minio.default.secoder.local:9000"
    S3_ACCESS_KEY: "IM_Admin_8w2P"
    S3_SECRET_KEY: "X9vM4cK7zL1qN5bY"
    S3_SECURE: "0"

    JWT_SECRET_KEY: "test_secret_for_cicd_only"
    DATABASE_URL: "postgresql://postgres:123456@postgres:5432/postgres"
    REDIS_URL: "redis://redis:6379/0"
  before_script:
    - apt-get update && apt-get install -y curl tar
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt coverage pytest pycodestyle pylint

unit-test:
  extends: .test
  script:
    # 🌟 拆除辅助轮：移除了 || true
    # 现在只要单测报错，流水线就会红，防止带着 Bug 的代码上线
    - coverage run -m pytest -s --junit-xml=xunit-reports/xunit-result.xml
    - ret=$?
    - coverage xml -o coverage-reports/coverage.xml
    - coverage report
    - exit $ret
  after_script:
    - SUFFIX=$RANDOM
    - echo "开始下载 Sonar Scanner..."
    - curl "http://api.spring26b.secoder.net/static/sonar-scanner.tar.gz" -L -o "/tmp/sonar-$SUFFIX.tar.gz"
    - echo "下载完成，开始解压..."
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz" -C /opt
    - echo "开始执行代码扫描..."
    - /opt/sonar-scanner/bin/sonar-scanner

style-test:
  extends: .test
  allow_failure: true # 依然允许风格不完美时不阻断流水线
  script:
    # 完美通过一号检查员 (pycodestyle)
    - pycodestyle --max-line-length=120 .
    - PYCODESTYLE_RET=$?
    # 🌟 核心修改：给二号检查员 (pylint) 戴上紧箍咒，只报致命错误，忽略 C, R, W
    - pylint --max-line-length=120 --disable=C,R,W .
    - PYLINT_RET=$?
    - if [ $PYCODESTYLE_RET \> 0 ]; then exit $PYCODESTYLE_RET; fi;
    - exit $PYLINT_RET

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - feat/cicd
    - dev