# 暂时用一个最通用的镜像，避开那个报错的 deployer
image: alpine:latest 

stages:
  - debug

check-registry-path:
  stage: debug
  script:
    - echo "系统内置的仓库地址是：$CI_REGISTRY"
    - echo "本项目的镜像全路径是：$CI_REGISTRY_IMAGE"
  only:
    - feat/cicd