# 1. 项目的唯一身份 ID（千万不要和别人的重名，建议全小写）
sonar.projectKey=ur-im-backend-69

# 2. 在 SonarQube 网页上显示的漂亮名字
sonar.projectName=UR-IM-Backend

# 3. 指定要扫描的源代码目录（"." 代表当前所有目录）
sonar.sources=.

# 4. 排除掉不需要检查代码质量的文件夹（非常重要！否则测试代码里的漏洞也会被算进去）
sonar.exclusions=tests/**, venv/**, .venv/**, xunit-reports/**, coverage-reports/**

# 5. 🌟 告诉 Sonar 去哪里读取我们刚才生成的覆盖率报告！
sonar.python.coverage.reportPaths=coverage-reports/coverage.xml